name: Code Quality

on:
  pull_request:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run flake8
        uses: peter-evans/flake8-action@v2
        with:
          max-line-length: 120
